### ISSUE TITLE
Getting a 500 internal server error

### ISSUE THREAD

**Issue by rvalkenaers** [ekesken/prom_marathon_exporter#3]
When scraping marathon I'm getting a server error. it seems to happen on following metric: "jvm.threads.deadlocks":{"value":[]} 

Stacktrace:
ERROR:http:Exception on /metrics [GET]
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functionsrule.endpoint
File "/prom_marathon_exporter/http.py", line 25, in metrics
prom_metrics = generate_latest(REGISTRY)
File "/usr/local/lib/python2.7/dist-packages/prometheus_client/exposition.py", line 67, in generate_latest
output.append('{0}{1} {2}\n'.format(name, labelstr, core._floatToGoString(value)))
File "/usr/local/lib/python2.7/dist-packages/prometheus_client/core.py", line 558, in _floatToGoString
elif math.isnan(d):
TypeError: a float is required

**Comment by ekesken** [comment]
Thanks for the issue.

I applied a private quick and dirty patch for prometheus_client to fix problem temporarily at Dockerfile, I'm closing the issue.
