### ISSUE TITLE
getting "TypeError: a float is required" for unexpected jvm.threads.deadlocks value "[]"

### ISSUE THREAD

**Issue by ekesken** [ekesken/prom_marathon_exporter#5]
```
Traceback (most recent call last):
  File "/d1/venv/prom_marathon_exporter/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/d1/venv/prom_marathon_exporter/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/d1/venv/prom_marathon_exporter/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/d1/venv/prom_marathon_exporter/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/d1/venv/prom_marathon_exporter/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/d1/venv/prom_marathon_exporter/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/d1/venv/prom_marathon_exporter/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/d1/venv/prom_marathon_exporter/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/d1/Dropbox/PycharmProjects/prom_marathon_exporter/http.py", line 24, in metrics
    prom_metrics = generate_latest(REGISTRY)
  File "/d1/venv/prom_marathon_exporter/lib/python2.7/site-packages/prometheus_client/exposition.py", line 55, in generate_latest
    for metric in registry.collect():
  File "/d1/venv/prom_marathon_exporter/lib/python2.7/site-packages/prometheus_client/core.py", line 55, in collect
    for metric in collector.collect():
  File "/d1/Dropbox/PycharmProjects/prom_marathon_exporter/collector.py", line 28, in collect
    if 'value' in marathon_metric and math.isnan(marathon_metric['value']):
TypeError: a float is required
```

**Comment by ekesken** [comment]
fixed with v0.2, closing the issue.
